epochs: 300
#batch_size: 250
batch_size: 64
n_steps: 16 # timestep
dataset: "CelebA"
in_channels: 3
#data_path: "./data"
data_path: "C:/Users/18741/Desktop/UIC/VAE/Data/"
lr: 0.001
latent_dim: 128 #64
input_size: 64
model: "PSVAE_large" # FSVAE or  FSVAE_large
k: 20 # multiplier of channel
scheduled: true # whether to apply scheduled sampling
loss_func: 'mmd' # mmd or kld


  